spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: server

server:
  port: 19090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost


